version: '3.7'
services:
  fabric-server-hsm:
    image: fabric-server-hsm:latest
    container_name: fabric-server-hsm
    restart: unless-stopped
    ports:
      - 3001:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - ./wallet:/app/wallet
      - ./connectionProfiles:/app/connectionProfiles

volumes:
  node_modules: